[package]
name = "plugin_devzat_forth"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
devzat-rs = "0.1.0"
tokio = { version = "1.19", features = ["macros", "rt-multi-thread"] }
lazy_static = "1.4.0"
libc = "0.2.139"

[build-dependencies]
cc = "1.0.46"

